AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template to create an Amazon SQS Standard Queue with default settings
  and SSE-SQS encryption.

Resources:
  DemoSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: demo-sqs
      KmsMasterKeyId: alias/aws/sqs
      MessageRetentionPeriod: 345600
      VisibilityTimeout: 30
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0

Outputs:
  QueueURL:
    Description: "URL of the created SQS Queue"
    Value: !Ref DemoSQSQueue

  QueueARN:
    Description: "ARN of the created SQS Queue"
    Value: !GetAtt DemoSQSQueue.Arn
