AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation Template to convert CSV to Parquet using AWS Lambda triggered by S3 file upload.

Parameters:
  LambdaS3Bucket:
    Type: String
    Description: S3 bucket where the Lambda deployment package is stored
  LambdaS3Key:
    Type: String
    Description: S3 key for the Lambda deployment package (e.g., lambda.zip)

Resources:
  CsvToParquetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: csvtoparquet
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CsvToParquetBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CsvToParquetBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${CsvToParquetBucket.Arn}/*"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CsvToParquetLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  CsvToParquetFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CsvToParquetLambda202501
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key

  S3LambdaTrigger:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CsvToParquetFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt CsvToParquetBucket.Arn

  S3Notification:
    Type: AWS::S3::BucketNotification
    Properties:
      Bucket: !Ref CsvToParquetBucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "interior/"
                  - Name: suffix
                    Value: ".csv"
            Function: !GetAtt CsvToParquetFunction.Arn

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      Tags:
        - Key: Name
          Value: demo-cloudformation
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3
