AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template for Airline Data Analytics with Amazon Athena.
  Creates S3 bucket, Glue database, IAM roles, and Athena WorkGroup.

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket for Athena data and results
    Default: laboratorio-athena-lscg-202502

Resources:
  # S3 Bucket for Athena Data and Results
  AthenaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # S3 Bucket Policy
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AthenaS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "s3:*"
            Resource:
              - !Sub arn:aws:s3:::${BucketName}
              - !Sub arn:aws:s3:::${BucketName}/*

  # AWS Glue Database for Athena
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: airline_data_analytics

  # IAM Role for Athena to Access S3
  AthenaQueryExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AthenaQueryExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: athena.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AthenaS3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*

  # Athena WorkGroup for Query Configuration
  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: AirlineDataWG
      State: ENABLED
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: !Sub s3://${BucketName}/result/
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        BytesScannedCutoffPerQuery: 1073741824 # 1GB limit for example

Outputs:
  S3BucketName:
    Description: S3 Bucket for storing CSV data and Athena query results
    Value: !Ref AthenaS3Bucket

  GlueDatabaseName:
    Description: Glue Database for Athena
    Value: !Ref GlueDatabase

  AthenaWorkGroupName:
    Description: Athena WorkGroup
    Value: !Ref AthenaWorkGroup

  AthenaIAMRoleARN:
    Description: IAM Role ARN for Athena
    Value: !GetAtt AthenaQueryExecutionRole.Arn
